# Generated by Django 5.2.11 on 2026-04-09 02:21

from django.db import migrations


def seed_educator_code(apps, schema_editor):
    EducatorAccessCode = apps.get_model('users', 'EducatorAccessCode')
    EducatorAccessCode.objects.get_or_create(
        code='CAPSTONE-2026',
        defaults={'is_active': True},
    )


def remove_educator_code(apps, schema_editor):
    EducatorAccessCode = apps.get_model('users', 'EducatorAccessCode')
    EducatorAccessCode.objects.filter(code='CAPSTONE-2026').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_educatoraccesscode_user_is_student_user_is_teacher_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_educator_code, remove_educator_code),
    ]

