# Generated by Django 5.2.11 on 2026-05-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='key',
            field=models.CharField(default='', help_text="Programmatic key, e.g. 'ch1_complete'", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
