# Generated by Django 5.2.11 on 2026-04-26 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_url', models.URLField(help_text='YouTube URL for the tutorial video')),
                ('topic', models.CharField(blank=True, default='', help_text='e.g., HTML, CSS, Django', max_length=50)),
                ('order', models.IntegerField(help_text='Display order among video tutorials')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InteractiveTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('topic', models.CharField(blank=True, default='', help_text='e.g., HTML, CSS, Django', max_length=50)),
                ('order', models.IntegerField(help_text='Display order among interactive tutorials')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisite', models.ForeignKey(blank=True, help_text='Another interactive tutorial that must be completed first', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='app.interactivetutorial')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InteractiveStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='HTML instructions shown to the student')),
                ('order', models.IntegerField()),
                ('file_type', models.CharField(choices=[('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('django', 'Django Template'), ('html+css', 'HTML + CSS')], default='python', max_length=20)),
                ('initial_code', models.TextField(blank=True, help_text='Starting code the student sees in the editor')),
                ('solution_code', models.TextField(help_text='Complete correct solution')),
                ('expected_elements', models.TextField(blank=True, help_text="JSON array of strings/patterns that must appear in the student's code")),
                ('base_template', models.TextField(blank=True, help_text="Content of base.html available via {% extends 'base.html' %}. Leave blank for default.", null=True)),
                ('preview_context', models.TextField(blank=True, help_text='JSON object of dummy variables for Django template previews e.g. {"title": "My Blog"}', null=True)),
                ('trivia', models.TextField(blank=True, help_text='Fun fact shown after the student completes this step', null=True)),
                ('checkpoint_xp', models.IntegerField(default=10, help_text='XP awarded for completing this step')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app.interactivetutorial')),
            ],
            options={
                'ordering': ['tutorial', 'order'],
                'unique_together': {('tutorial', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserInteractiveEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.interactivestep')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app.interactivetutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tutorial')},
            },
        ),
        migrations.CreateModel(
            name='UserVideoEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_enrollments', to=settings.AUTH_USER_MODEL)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app.videotutorial')),
            ],
            options={
                'unique_together': {('user', 'tutorial')},
            },
        ),
        migrations.CreateModel(
            name='VideoStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Text log describing what is covered at this point in the video')),
                ('order', models.IntegerField()),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app.videotutorial')),
            ],
            options={
                'ordering': ['tutorial', 'order'],
                'unique_together': {('tutorial', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserStepSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('attempt_count', models.IntegerField(default=1)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_submissions', to='app.userinteractiveenrollment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.interactivestep')),
            ],
            options={
                'unique_together': {('enrollment', 'step')},
            },
        ),
        migrations.CreateModel(
            name='UserVideoStepView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_views', to='app.uservideoenrollment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.videostep')),
            ],
            options={
                'unique_together': {('enrollment', 'step')},
            },
        ),
    ]
