# Generated by Django 5.1.6 on 2025-03-03 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='app.tutorial')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TutorialStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='HTML content with instructions')),
                ('order', models.IntegerField()),
                ('file_type', models.CharField(choices=[('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('django', 'Django Template')], default='python', max_length=20)),
                ('initial_code', models.TextField(blank=True, help_text='Starting code the user will see')),
                ('solution_code', models.TextField(help_text='Complete solution code')),
                ('expected_elements', models.TextField(blank=True, help_text="JSON array of strings or patterns that should be in user's code")),
                ('checkpoint_xp', models.IntegerField(default=10, help_text='XP awarded for completing this step')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app.tutorial')),
            ],
            options={
                'ordering': ['tutorial', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserStepSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('attempt_count', models.IntegerField(default=1)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutorialstep')),
            ],
        ),
        migrations.CreateModel(
            name='UserTutorialEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.tutorialstep')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutorial')),
            ],
        ),
    ]
