# Generated by Django 5.2.11 on 2026-04-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteractiveenrollment',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='userstepsubmission',
            name='step',
        ),
        migrations.RemoveField(
            model_name='interactivetutorial',
            name='prerequisite',
        ),
        migrations.RemoveField(
            model_name='userinteractiveenrollment',
            name='tutorial',
        ),
        migrations.AlterUniqueTogether(
            name='userinteractiveenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userinteractiveenrollment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstepsubmission',
            name='enrollment',
        ),
        migrations.AlterUniqueTogether(
            name='userstepsubmission',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='InteractiveStep',
        ),
        migrations.DeleteModel(
            name='InteractiveTutorial',
        ),
        migrations.DeleteModel(
            name='UserInteractiveEnrollment',
        ),
        migrations.DeleteModel(
            name='UserStepSubmission',
        ),
    ]
