# Generated by Django 5.1.6 on 2025-03-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialstep',
            name='trivia',
            field=models.TextField(blank=True, help_text='Trivia shown after completing this step', null=True),
        ),
    ]
