# Generated by Django 5.1.6 on 2025-03-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tutorialstep_trivia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialstep',
            name='file_type',
            field=models.CharField(choices=[('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('django', 'Django Template'), ('html+css', 'HTML + CSS')], default='python', max_length=20),
        ),
    ]
