# Generated by Django 5.2.11 on 2026-04-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tutorialstep_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialstep',
            name='base_template',
            field=models.TextField(blank=True, help_text="Content of base.html available to the student's template via {% extends 'base.html' %}. Leave blank to use the default base template.", null=True),
        ),
        migrations.AddField(
            model_name='tutorialstep',
            name='preview_context',
            field=models.TextField(blank=True, help_text='JSON object of dummy variables to pass when rendering django template previews (e.g. {"title": "My Blog", "posts": [{"title": "Post 1"}]})', null=True),
        ),
    ]
