# Generated by Django 5.2.11 on 2026-04-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesave',
            name='ch1_did_remedial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesave',
            name='ch1_quiz_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesave',
            name='ch1_remedial_score',
            field=models.IntegerField(default=0),
        ),
    ]
