# Generated by Django 5.2.11 on 2026-04-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0002_gamesave_ch1_did_remedial_gamesave_ch1_quiz_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesave',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesave',
            name='defeated_npcs',
            field=models.IntegerField(default=0),
        ),
    ]
