# Generated by Django 5.2.11 on 2026-05-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0003_gamesave_credits_gamesave_defeated_npcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesave',
            name='thesis_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesave',
            name='thesis_panelist_progress',
            field=models.IntegerField(default=0),
        ),
    ]
